### ISSUE TITLE
Add a static list of nouns to the api project

### ISSUE THREAD

**Issue by jpdillingham** [qccoders/startup-idea-generator#16]
Add a function `getNounList()` that returns an array of nouns as a string.

Include 10 nouns to start; we'll add more later.  Consider using https://www.ef.edu/english-resources/english-vocabulary/top-50-nouns/ for inspiration.

**Comment by kolec94** [comment]
I don't see where to assign this to myself?

**Comment by brian-guerrero** [comment]
@kolec94 in the top right corner you should see a settings icons next to assignees if you are a member of this repo.
