### ISSUE TITLE
Choose UI framework

### ISSUE THREAD

**Issue by jpdillingham** [qccoders/startup-idea-generator#19]
Use the comments for this issue to suggest and evaluate various UI frameworks for the application.

We'll want to choose something that includes a good set of React components.

**Comment by brian-guerrero** [comment]
How about [Semantic UI](https://react.semantic-ui.com/) for React? The component markup seems pretty straightforward, and I think it looks better than Material UI. Thoughts?

**Comment by brian-guerrero** [comment]
Sounds good, @jpdillingham! What's our timeline for picking a framework?

**Comment by jpdillingham** [comment]
Let's call it good now; we'll use Semantic UI.
