### ISSUE TITLE
Allow users to 'pin' either side of the generator

### ISSUE THREAD

**Issue by jpdillingham** [qccoders/startup-idea-generator#53]
Presently you get a random startup + noun pairing when you generate a startup.  It would be nice to be able to 'pin' either the startup or the noun so it stays the same each time, while the other continues to be randomly generated.

We should be able to persist 'pinnings' in either local storage, or could potentially save it in the URL.

**Comment by jpdillingham** [comment]
I just realized this is a duplicate of #43.  It has some good ideas so I'll leave both open.

**Comment by Kedap** [comment]
What code formatter do you use? Use prettier and format all the code again while I was writing new code.

**Comment by jpdillingham** [comment]
Prettier is fine, thanks!
